version: '3.8'

services:
  claude-batch-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: claude-batch-server
    privileged: true
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - workspace-repos:/workspace/repos
      - workspace-jobs:/workspace/jobs
      - app-logs:/var/log/claude-batch-server
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/group:/etc/group:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - Jwt__Key=${JWT_KEY:-YourSuperSecretJwtKeyThatShouldBe32CharactersOrLonger!}
      - Workspace__RepositoriesPath=/workspace/repos
      - Workspace__JobsPath=/workspace/jobs
      - Jobs__MaxConcurrent=${MAX_CONCURRENT_JOBS:-5}
      - Jobs__TimeoutHours=${JOB_TIMEOUT_HOURS:-24}
      - Claude__Command=claude
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: claude-batch-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - claude-batch-server

volumes:
  workspace-repos:
    driver: local
  workspace-jobs:
    driver: local
  app-logs:
    driver: local
  nginx-logs:
    driver: local

networks:
  default:
    name: claude-batch-network